### ISSUE TITLE
support for usb-20X

### ISSUE THREAD

**Issue by eidmanna** [gotmc/mccdaq#2]
I would need support for the model USB 200 Serie (USB 201).

http://www.mccdaq.com/usb-data-acquisition/USB-200-OEM-Series.aspx.

What is the plan for supporting other models? A new package for each model?

**Comment by matthewrankin** [comment]
> What is the plan for supporting other models? A new package for each model?

Yes. I was thinking we could create `github.com/gotmc/mccdaq/usb200oem` and similar packages. As more models are supported, then we might need to pull out common code into a support package, such as `github.com/gotmc/mccdaq/common` or something.

**Comment by matthewrankin** [comment]
@eidmanna I've merged (commit 93e4128520b9edb1c28c3ec48d7ff0ef351806fc) a first attempt at supporting the USB 200 Series devices into master. I've only added the support for reading the 8-ch analog inputs (i.e., currently there's no digital I/O or analog output support). I don't have a USB 200 Series device, so you'll have to let me know what failures there are. Thanks.

**Comment by eidmanna** [comment]
@matthewrankin Thx for your effort. I'll test it soon.

**Comment by matthewrankin** [comment]
Closing for now to clean up open issues.
